// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeSheetManager_services.Data;

#nullable disable

namespace TimeSheetManager_services.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TimeSheetManager_services.Models.Employee", b =>
                {
                    b.Property<int>("EMP_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EMP_ID"));

                    b.Property<DateTime>("CREATED_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMP_AADHAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMP_ADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMP_ALT_PHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMP_CITY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMP_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMP_COUNTRY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EMP_EXIT_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMP_FIRSTNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMP_GMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EMP_HIREDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMP_LASTNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EMP_LAST_LOGIN")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMP_LOCATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EMP_MGR_NO")
                        .HasColumnType("int");

                    b.Property<string>("EMP_PAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMP_PASSWORD_HASH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMP_PHONE")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("EMP_PROJECT_ID")
                        .HasColumnType("int");

                    b.Property<string>("EMP_ROLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EMP_SALARY")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("EMP_SHIFT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMP_STATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMP_STATUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EMP_TEAM_ID")
                        .HasColumnType("int");

                    b.Property<string>("EMP_WORK_MODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UPDATED_AT")
                        .HasColumnType("datetime2");

                    b.HasKey("EMP_ID");

                    b.ToTable("EMPLOYEE", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
